name: TESTING_PVS_CI

on: [push, pull_request]

jobs:
  pvs-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Installing PVS-Studio
      run: |
        sudo add-apt-repository ppa:ubuntu-lxc/daily -y
        wget -q -O - https://files.viva64.com/etc/pubkey.txt |sudo apt-key add -
        sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
        sudo apt-get update -qq
        sudo apt-get install -qq coccinelle parallel python3-setuptools docbook2x pvs-studio sendemail ca-certificates
        pvs-studio-analyzer credentials "PVS-Studio Free" "FREE-FREE-FREE-FREE" -o PVS-Studio.lic
    - name: Run PVS check
      run: |
        cd HoloApp
        pvs-studio-analyzer analyze -j2 -l PVS-Studio.lic -o PVS-Studio.log --disableLicenseExpirationCheck
        plog-converter -t html PVS-Studio.log -o PVS-Studio.html
    - name: Mailing report
      run: sendemail -t krasnovpavel0@gmail.com 
            -u "PVS-Studio report, commit:$GITHUB_SHA" 
            -m "PVS-Studio report, commit:$GITHUB_SHA" 
            -s smtp.gmail.com:587 
            -xu krasnovpavel0
            -xp USSEnterprise1701 
            -o tls=yes 
            -f krasnovpavel0 
            -a PVS-Studio.log PVS-Studio.html
